### ISSUE TITLE
Are MO files really needed for translation?

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_imprint#11]
Are the MO files really needed for translation?

I ask this because it seems that other modules (like [webtrees-fancy-treeview/resources/lang/](https://github.com/JustCarmen/webtrees-fancy-treeview/tree/main/resources/lang)) don't need them.

**Comment by hartenthaler** [comment]
You are right: in the GitHub repository [webtrees-fancy-treeview/resources/lang/](https://github.com/JustCarmen/webtrees-fancy-treeview/tree/main/resources/lang) there is only one .mo file. But if you download this module as a release then there are all the .mo files.
For the providing of the translated strings in PHP, only the .mo files are important. The .po files are only for the human translator necessary.
I'm still struggling with the usage of https://poeditor.com. I will prefer the usage of this online tool, but the process is not perfect up to now.
