### ISSUE TITLE
Unused translation string: other

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_imprint#14]
One translated string is not used: [other](https://github.com/hartenthaler/hh_imprint/blob/1dd808f1a5bb8f9746a45f34f82453b62d48fce3/resources/lang/nl.po#L92)

In Dutch I translated it with `overig`, but it shows `andere`.

**Comment by hartenthaler** [comment]
In German, the translation for this third type of sex is "divers".

**Comment by TheDutchJewel** [comment]
Why is the sex/gender of the responsible person relevant?

If it is not required, make it optional or remove it.

**Comment by hartenthaler** [comment]
The body of the generated eMail contains "Dear Mr. Xxx" or "Dear Mrs."  Therefor it is needed. Maybe not so important.
