### ISSUE TITLE
2.1.8.1 Fatal error "The parameter “tree” is missing".

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_imprint#15]
With webtrees 2.1.9, XAMPP 8.0.25 and only the `hh_imprint` module enabled I get this fatal error

`Fatal error: Uncaught Fisharebest\Webtrees\Http\Exceptions\HttpBadRequestException: The parameter “tree” is missing. in D:\xampp\htdocs\webtrees-test\app\Validator.php:363 Stack trace: #0 D:\xampp\htdocs\webtrees-test\modules_v4\hh_imprint\module.php(297): Fisharebest\Webtrees\Validator->tree() #1 D:\xampp\htdocs\webtrees-test\resources\views\layouts\default.phtml(140): Fisharebest\Webtrees\Module\PrivacyPolicy@anonymous->getFooter(Object(Nyholm\Psr7\ServerRequest)) #2 [internal function]: Fisharebest\Webtrees\View::{closure}(Object(Fisharebest\Webtrees\Module\PrivacyPolicy@anonymous), '_hh_imprint_') #3 D:\xampp\htdocs\webtrees-test\vendor\illuminate\collections\Collection.php(695): array_map(Object(Closure), Array, Array) #4 D:\xampp\htdocs\webtrees-test\resources\views\layouts\default.phtml(141): Illuminate\Support\Collection->map(Object(Closure)) #5 D:\xampp\htdocs\webtrees-test\app\View.php(183): include('D:\\xampp\\htdocs...') #6 D:\xampp\htdocs\webtrees-test\app\View.php(278): Fisharebest\Webtrees\View->render() #7 D:\xampp\htdocs\webtrees-test\app\Helpers\functions.php(145): Fisharebest\Webtrees\View::make('layouts/default', Array) #8 D:\xampp\htdocs\webtrees-test\app\Http\ViewResponseTrait.php(54): view('layouts/default', Array) #9 D:\xampp\htdocs\webtrees-test\app\Http\Middleware\HandleExceptions.php(171): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->viewResponse('components/aler...', Array, 400) #10 D:\xampp\htdocs\webtrees-test\app\Http\Middleware\HandleExceptions.php(99): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->httpExceptionResponse(Object(Nyholm\Psr7\ServerRequest), Object(Fisharebest\Webtrees\Http\Exceptions\HttpBadRequestException)) #11 D:\xampp\htdocs\webtrees-test\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #12 D:\xampp\htdocs\webtrees-test\app\Http\Middleware\BaseUrl.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #13 D:\xampp\htdocs\webtrees-test\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #14 D:\xampp\htdocs\webtrees-test\app\Http\Middleware\ReadConfigIni.php(68): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #15 D:\xampp\htdocs\webtrees-test\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #16 D:\xampp\htdocs\webtrees-test\app\Http\Middleware\SecurityHeaders.php(48): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #17 D:\xampp\htdocs\webtrees-test\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #18 D:\xampp\htdocs\webtrees-test\app\Http\Middleware\EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #19 D:\xampp\htdocs\webtrees-test\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #20 D:\xampp\htdocs\webtrees-test\vendor\oscarotero\middleland\src\Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #21 D:\xampp\htdocs\webtrees-test\app\Webtrees.php(275): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) #22 D:\xampp\htdocs\webtrees-test\app\Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array) #23 D:\xampp\htdocs\webtrees-test\index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest() #24 {main} thrown in D:\xampp\htdocs\webtrees-test\app\Validator.php on line 363`

**Comment by hartenthaler** [comment]
In the meantime, I modified this part of the module, so that it is now hard to reconstruct the situation. I will release a new version tomorrow. Please reopen this issue when the error will be still there.

**Comment by hartenthaler** [comment]
I found this error now in my test environment, but up to now, I don't know why it happens.

**Comment by fisharebest** [comment]
See https://github.com/hartenthaler/hh_imprint/blob/7c7ab9d75cac75fcb33322df20db63e4367ec1cc/ImprintFooterModule.php#L324-L325

Some pages do not have a `tree` parameter.  For example, the login page when all trees are private.

You should use `treeOptional()` instead of `tree()`.
You should also remove the `assert()`, because `$tree` can be null.

**Comment by Morph3us2** [comment]
> You should use `treeOptional()` instead of `tree()`.

Fixes the error in my environment.

**Comment by hartenthaler** [comment]
should be fixed in the next release
