### ISSUE TITLE
translation of "Impressum" 

### ISSUE THREAD

**Issue by LarsRabe** [hartenthaler/hh_imprint#17]
A remark: using "IMPRINT" as english translation for "IMPRESSUM" is not correct on a website. The correct translation is "LEGAL NOTICE" or (less common) "LEGAL DISCLOSURE".

See e.g.
https://language-boutique.de/naithani/blogpost/impressum-auf-englisch.html
https://fluentlylegal.com/was-heist-impressum-auf-englisch/
https://superior-english.com/2020/12/09/wie-uebersetzt-man-impressum-ins-englische/

**Comment by hartenthaler** [comment]
You are right. It is like "Handy" versus "mobile phone".

**Comment by LarsRabe** [comment]
I thought also about the dutch translation as "impressum" isn't existing in this usecase as well. Probably better would be "Juridische Kennisgeving", which is the translation for "Legal Notice".

**Comment by hartenthaler** [comment]
This module will be renamed in the next release.

**Comment by hartenthaler** [comment]
solved with release 2.2.1.0
