### ISSUE TITLE
Dutch translation of "Copyright" is shown as "Copy right" 

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_imprint#18]
I have translated the header "Copyright" in Dutch into "Auteursrecht".

But instead of "Auteursrecht"  I see "Copy right" (in English, with a space)::

![afbeelding](https://user-images.githubusercontent.com/46184729/212145589-98e86bdc-4771-49dd-a8a7-cd682007a729.png)

**Comment by hartenthaler** [comment]
I noticed already that I used "copy right" and "copyright" in the English original text. Maybe this is the reason.

**Comment by TheDutchJewel** [comment]
Thanks: the new string solved this problem!
