### ISSUE TITLE
Alignment imprint issue with Rural theme

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_imprint#19]
Alignment problem of the hh_imprint module (2.1.15.1) with the Rural theme:

![afbeelding](https://user-images.githubusercontent.com/46184729/212150250-108ae3e1-ff08-4b35-9bd6-673019b6219d.png)

![afbeelding](https://user-images.githubusercontent.com/46184729/212150373-62e456e6-29c6-4f98-8c03-c407924eb83e.png)

**Comment by hartenthaler** [comment]
Yes, that should not be centred. I fixed that already for other elements, but have forgotten those new ones.

**Comment by hartenthaler** [comment]
fixed in next release
