### ISSUE TITLE
make wt 2.2 compatible

### ISSUE THREAD

**Issue by arbor95** [hartenthaler/hh_imprint#21]
Fatal error in module: imprint
Error: Call to undefined function app() in /..../webtrees/modules_v4/imprint/module.php:66 Stack trace: #0

**Comment by hartenthaler** [comment]
Dieses Modul ist noch nicht umgestellt. Es wird es das nächste sein. Nach einem Jahr ohne Programmieren musste ich erst einmal meine Entwicklungsumgebung reaktivieren. Nun steht sie wieder und ich habe zum Probieren ein kleines Test-Modul umgestellt (german-chancellors-presidents).

**Comment by hartenthaler** [comment]
solved with release 2.2.1.0
