### ISSUE TITLE
Text suggestion

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_imprint#3]
Under the heading `Respondible person` there are three items that all relate to the Respondible person. Therefore, the text `or respondible person` after 'Sex' can be removed.

![afbeelding](https://user-images.githubusercontent.com/46184729/204315465-a27d786f-3479-4026-991b-5d40711045aa.png)

**Comment by hartenthaler** [comment]
Good, and I will move Registration data to the bottom.

**Comment by hartenthaler** [comment]
fixed
