### ISSUE TITLE
Alignment imprint issue with Rural theme

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_imprint#9]
The Imprint looks fine in all themes, except the Rural theme;

Example with default webtrees theme:
![afbeelding](https://user-images.githubusercontent.com/46184729/204536223-af7d1854-6148-44a9-9b55-903e1cec9e66.png)

Example with [Rural theme](https://github.com/jon48/webtrees-theme-rural):
![afbeelding](https://user-images.githubusercontent.com/46184729/204536432-680aef34-1e85-4b52-b373-14577a790d02.png)

**Comment by hartenthaler** [comment]
solved! Now it looks ok for all themes besides "modern"
